name: Our First Workflow
# name 키를 생략하면 파일 경로가 워크플로우 이름으로 사용됨
# 반드시 설정해줘야 하는 것은 아니지만, name 키를 명시하여 워크플로우에 알맞은 이름 부여해주는 것이 일반적

on: push
# 필수 항목
# 워크플로우가 언제 실행되어야할지 설정해줘야 함
# 일반적으로 코드 저장소에서 어떤 이벤트가 발생할 때 마다 워크플로우를 자동으로 촉발(trigger)하도록 설정
# push -> 누군가 코드 저장소에 변경 사항을 push하거나 pull request가 merge 될 때마다 해당 워크플로우 자동 실행

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hello, GitHub Actions!'
# 워크 플로우에서 어떤 작업들을 수행할지 jobs 키를 통해 설정
# jobs 키에는 여러 개의 작업을 작업 식별자(ID)와 작업 세부 내용 간의 mapping 형태로 표시
# 예시: 콘솔에 Hello, GitHub Actions! 를 출력하는 echo라는 식별자를 가진 작업 하나 추가